### PR TITLE
Update package name in README

### PR DESCRIPTION
**Pull request by robdimsdale**
To configure concourse worker with the correct image.

### CODE REVIEW

**Comment by joek** [comment]
here you go:

```
...
lrwxrwxrwx  1 root root  124 Nov 30 12:21 archive_resource -> /var/vcap/data/packages/archive_resource/bccfe78d8e898f5f946d3364ee559e4ae339efd9.1-7be1dbf936d9369d5b3dc11cc94d9fde8158b7aa
lrwxrwxrwx  1 root root  117 Nov 30 12:21 bosh-init -> /var/vcap/data/packages/bosh-init/c4a706a00cc3b2132df05008340511fc418c9257.1-4c2711133aa6fb4ee1bc905ee1c95d9533aca8f3
lrwxrwxrwx  1 root root  132 Nov 30 12:21 bosh_deployment_resource -> /var/vcap/data/packages/bosh_deployment_resource/67cb031ef64ad2def28507920e70714297c52b7c.1-b45c52348b510c8bb79324e9136cdd678b00b399
...
```

We are using 0.68.0 too and the latest version of the bosh-init resource.

**Comment by robdimsdale** [comment]
Yes that is exactly what I see as well, which is why I made this PR - concourse needs to know the correct filesystem location of the package and that example part of the concourse manifest was incorrect in the README.

Looks like I'm not the only one who ran into this - https://github.com/hybris/bosh-init-deployment-resource/issues/2

I would be interested in the contents of the manifest; could you `bosh download manifest` and paste the relevant lines here?

Thanks

**Comment by joek** [comment]
I am not sure, if you mixed up the lines, but there is a bosh-init link / folder in there which is != bosh-init-deployment-resource. 

```
lrwxrwxrwx  1 root root  117 Nov 30 12:21 bosh-init -> /var/vcap/data/packages/bosh-init/c4a706a00cc3b2132df05008340511fc418c9257.1-4c2711133aa6fb4ee1bc905ee1c95d9533aca8f3
```

Here is the snipped out of my manifest file:

```
    properties:
      garden:
        disk_quota_enabled: false
        listen_network: tcp
        listen_address: 0.0.0.0:7777
        btrfs_store_size_mb: 75000
      groundcrew:
        additional_resource_types:
        - type: victorops-notification
          image: /var/vcap/packages/victorops-notification-resource
        - type: bosh-init-deployment
          image: /var/vcap/packages/bosh-init
        - type: statuspage-notification
          image: /var/vcap/packages/statuspage-notification-resource
```

It makes already use of the new `additional_resource_types` property. This is something I have to change in the README. Everything else should work.

**Comment by robdimsdale** [comment]
I think we are saying exactly the same thing; that the section about adding to the concourse manifest in the README needs to be updated - that is what this pull request addresses.

With this PR, a user can follow the README from top-to bottom and adding the necessary, functional changes to the concourse manifest required to get concourse to correctly locate the package on disk. Currently, this is not the case. The manifest snippet you posted cannot be created with the README in its current state, and this PR addresses that.

If you feel like you understand the necessary changes to the README to enable a consumer to update the README, please close this PR and make them yourself. Otherwise, please let me know how else I can help you understand this PR.

**Comment by joek** [comment]
Oh, shit sorry, I mixed red and green (facepalm). Will merge it soon.

**Comment by robdimsdale** [comment]
No problem. Glad we were on the same page. Thanks for merging!

**Pull request merged**
